### ISSUE TITLE
Possible to install Pointcloud on Windows?

### ISSUE THREAD

**Issue by BenoitDalFerro** [pgpointcloud/pointcloud#116]
Hi,

I'm trying to play a bit to learn Pointcloud, is there any way to install it on Windows?

Best regards,

Ben

**Comment by BenCEEME** [comment]
Is that the answer to my question?
http://pointclouds.org/downloads/windows.html

**Comment by BenCEEME** [comment]
Nope seems its a separate project

**Comment by BenoitDalFerro** [comment]
Apparently there is this OpenGeo suite with Pointcloud installed a default:

http://suite.opengeo.org/docs/latest/dataadmin/pointcloud/install.html

However if I just want to keep my OSGeo64W and my PostgreSQL/PostGIS install how do I do?

It says it is default shipping with PostGIS maybe my PostGIS is too old, let's try re-installing

**Comment by BenoitDalFerro** [comment]
Wonderful re-installed PostGIS and it worked!
In fact pointcloud is really shipped as default.
