### ISSUE TITLE
Master not compiling against PostgreSQL 9.6

### ISSUE THREAD

**Issue by pjduplooy** [pgpointcloud/pointcloud#118]
Hi guys.  

I am trying to compile Master against PostgreSQL 9.6, and am experiencing some compile problems.

PostgreSQL was installed from the pgdg apt.
Postgis, laz-perf and libght compiled from source.
All other deps installed from repositories. (Ubuntu 16.04.1 and osgeolive ppa for gdal and others)

The errors I get are:

[ 90%] Building C object pgsql/CMakeFiles/pointcloud.dir/pc_access.c.o
In file included from /usr/include/postgresql/9.6/server/access/heapam.h:22:0,
                 from /usr/include/postgresql/9.6/server/nodes/execnodes.h:18,
                 from /usr/include/postgresql/9.6/server/executor/execdesc.h:18,
                 from /usr/include/postgresql/9.6/server/executor/executor.h:17,
                 from /usr/include/postgresql/9.6/server/funcapi.h:21,
                 from /home/pieter/Temp/pointcloud/pgsql/pc_access.c:14:
/usr/include/postgresql/9.6/server/storage/lock.h:18:2: error: #error "lock.h may not be included from frontend code"
 #error "lock.h may not be included from frontend code"
  ^
In file included from /usr/include/postgresql/9.6/server/storage/lock.h:23:0,
                 from /usr/include/postgresql/9.6/server/access/heapam.h:22,
                 from /usr/include/postgresql/9.6/server/nodes/execnodes.h:18,
                 from /usr/include/postgresql/9.6/server/executor/execdesc.h:18,
                 from /usr/include/postgresql/9.6/server/executor/executor.h:17,
                 from /usr/include/postgresql/9.6/server/funcapi.h:21,
                 from /home/pieter/Temp/pointcloud/pgsql/pc_access.c:14:
/usr/include/postgresql/9.6/server/storage/lwlock.h:18:2: error: #error "lwlock.h may not be included from frontend code"
 #error "lwlock.h may not be included from frontend code"
  ^
In file included from /usr/include/postgresql/9.6/server/storage/lwlock.h:22:0,
                 from /usr/include/postgresql/9.6/server/storage/lock.h:23,
                 from /usr/include/postgresql/9.6/server/access/heapam.h:22,
                 from /usr/include/postgresql/9.6/server/nodes/execnodes.h:18,
                 from /usr/include/postgresql/9.6/server/executor/execdesc.h:18,
                 from /usr/include/postgresql/9.6/server/executor/executor.h:17,
                 from /usr/include/postgresql/9.6/server/funcapi.h:21,
                 from /home/pieter/Temp/pointcloud/pgsql/pc_access.c:14:
/usr/include/postgresql/9.6/server/storage/s_lock.h:100:2: error: #error "s_lock.h may not be included from frontend code"
 #error "s_lock.h may not be included from frontend code"
  ^
In file included from /usr/include/postgresql/9.6/server/storage/lwlock.h:23:0,
                 from /usr/include/postgresql/9.6/server/storage/lock.h:23,
                 from /usr/include/postgresql/9.6/server/access/heapam.h:22,
                 from /usr/include/postgresql/9.6/server/nodes/execnodes.h:18,
                 from /usr/include/postgresql/9.6/server/executor/execdesc.h:18,
                 from /usr/include/postgresql/9.6/server/executor/executor.h:17,
                 from /usr/include/postgresql/9.6/server/funcapi.h:21,
                 from /home/pieter/Temp/pointcloud/pgsql/pc_access.c:14:
/usr/include/postgresql/9.6/server/port/atomics.h:41:2: error: #error "atomics.h may not be included from frontend code"
 #error "atomics.h may not be included from frontend code"
  ^
/home/pieter/Temp/pointcloud/pgsql/pc_access.c: In function ‘pcpatch_unnest’:
/home/pieter/Temp/pointcloud/pgsql/pc_access.c:506:16: warning: implicit declaration of function ‘MemoryContextSwitchTo’ [-Wimplicit-function-declaration]
   oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
                ^
/home/pieter/Temp/pointcloud/pgsql/pc_access.c:506:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   oldcontext = MemoryContextSwitchTo(funcctx->multi_call_memory_ctx);
              ^
In file included from /home/pieter/Temp/pointcloud/pgsql/pc_access.c:16:0:
/home/pieter/Temp/pointcloud/pgsql/pc_access.c: At top level:
/home/pieter/Temp/pointcloud/lib/pc_api_internal.h:285:20: warning: inline function ‘pc_bitmap_set’ declared but never defined
 extern inline void pc_bitmap_set(PCBITMAP _map, int i, int val);
                    ^
pgsql/CMakeFiles/pointcloud.dir/build.make:62: recipe for target 'pgsql/CMakeFiles/pointcloud.dir/pc_access.c.o' failed
make[2]: *_\* [pgsql/CMakeFiles/pointcloud.dir/pc_access.c.o] Error 1
CMakeFiles/Makefile2:238: recipe for target 'pgsql/CMakeFiles/pointcloud.dir/all' failed
make[1]: **\* [pgsql/CMakeFiles/pointcloud.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

Any help would be appreciated!!

Regards
Pieter

**Comment by pramsey** [comment]
Sorry, don't have a lot of free time to devote to this. @strk seems to be maintaining autoconf build but maybe not so much cmake? An autoconf build worked for me, try that instead for now
```
./autogen.sh
./configure
```

**Comment by achidlow** [comment]
Hi @pjduplooy, I had the same issue upgrading to 9.6 on Debian. It's to do with the output of `pg_config --cppflags` changing to include `-DFRONTEND`. 

However I don't think pgpointcloud should be using this anyway, pgpointcloud is C so I'm pretty sure it should be using the output of `pg_config --cflags` instead (which doesn't include `-DFRONTEND`).

I've submitted a pull request with this fix just now.

**Comment by yazun** [comment]
thanks, I was just about to do the same, but for me removing all pkg-references and adding 

PG_CPPFLAGS= $(shell $(PG_CONFIG) --cflags ) -I $(shell $(PG_CONFIG) --includedir)

worked.

cheers

**Comment by elemoine** [comment]
With https://github.com/pgpointcloud/pointcloud/pull/119 now closed this issue can be closed as well.

**Comment by strk** [comment]
Thanks
