### ISSUE TITLE
How are pcpatches stored?

### ISSUE THREAD

**Issue by kozuch** [pgpointcloud/pointcloud#120]
I must admit I do not understand why pcpatch exist at all. The docs here say "storing billions of points as individual records in a table is not an efficient use of resources". I can understand this even though for instance OpenStreetMap seems to have a single Postgres table for nodes and they have 3.5 billion of them without any problem.

Can someone tell me how entries in patch table look like? Seems like there is a dedicated data types PCPOINT and PCPATCH - are they described somewhere?

CREATE TABLE patches (
    id SERIAL PRIMARY KEY,
    **pa PCPATCH(1)**
);

In [this video](https://youtu.be/8MiJkvXpET4?t=4m43s) the pcpoint format (data type) is described - is the pcpatch format constructed in a similar way (forming finally a string)? I mean like it may be coded that the patch contains X points at the beginning of the string and then simply individual points would be concatenated one after another...

Thanks for reply!

**Comment by Remi-C** [comment]
Hey @kozuch ,
here is a presentation with detailed comments on pgpointcloud.
https://github.com/Remi-C/Postgres_Day_2014_10_RemiC/raw/master/presentation/A%20PostgreSQL%20Server%20for%20Point%20Cloud%20Storage%20and%20Processing.pdf

The part about storage is around p21.
Cheers,
Rémi-C
