### ISSUE TITLE
Geometry(pcpatch) disappeared while PC_Envelope(pcpatch) changed output type

### ISSUE THREAD

**Issue by tomvantilburg** [pgpointcloud/pointcloud#168]
Updating to master, I found out that the function Geometry(pcpatch) is gone and seemingly replaced by PC_Envelope. Is this on purpose?
On top of this, PC_Envelope changed it's output type (from bytea to geometry) which makes it impossible to upgrade my existing database.

I understand updating to master is at my own risk, but this is a rather painful change. Would a workaround be available?

**Comment by mbredif** [comment]
#149 renamed the bytea-returning PC_Envelope as PC_EnvelopeAsBinary and the geometry cast as a geometry-returning PC_Envelope. this was motivated by issue #30 and to make the return types more consistent with the equivalent postgis function.

#164 proposes to add the geometry cast back (for backward compatibility only) to deprecate it instead of removing it altogether. Please vote for it if renaming the geometry cast with a PC_Envelope function is not a good solution for you.

**Comment by tomvantilburg** [comment]
After some consideration I think it's okay for me to drop the old extension and reload my data since everything was in development stage. I can imagine that some people that have a production system would be grateful with backwards compatibility so I'll vote +1 anyway.

**Comment by elemoine** [comment]
https://github.com/pgpointcloud/pointcloud/pull/164 adds back the `geometry(pcpatch)` function, which  think we should merge.

But the return type change for `PC_Envelope` still breaks the backward compatiblity. People who've used `PC_Envelope` should now use `PC_EnvelopeAsBinary`. I feel bad about breaking backward compatibility here, but at the same time I also think that the new API is better. We should at least have release notes somewhere I guess.

**Comment by tomvantilburg** [comment]
Ah yes, that's true. I guess the biggest issue here is that you would have to rebuild indexes that rely on PC_Envelope (and likely some update fuss with replacing functions that have a new output type).

**Comment by elemoine** [comment]
@tomvantilburg good point on the necessity of rebuilding indexes. @mbredif I'd like us to think about this and take this backward compatibility stuff seriously.

**Comment by elemoine** [comment]
@tomvantilburg I guess you are referring to indexes created using `USING GIST(ST_GeomFromEWKB(PC_Envelope(patch)))` that now need to be `USING GIST(PC_Envelope(patch))`. Right?`

**Comment by tomvantilburg** [comment]
Almost, my former index was:  ```USING gist (geometry(pa));```
I think that came from a very old example some time ago.

**Comment by elemoine** [comment]
Ok, so I guess that adding back the `Geometry(pcpatch)` function (https://github.com/pgpointcloud/pointcloud/pull/164) would have been sufficient in your case. Re-creating the index would not have been necessary.

But we will break `USING GIST(ST_GeomFromEWKB(PC_Envelope(patch)))` with the new `PC_Envelope` return type, and https://github.com/pgpointcloud/pointcloud/pull/164 is not fixing that.

**Comment by tomvantilburg** [comment]
Yes, that may have been sufficient :)

There is this other thing that you cannot simply replace a function when the output type changes in postgres. This results in having to drop the function (PC_Envelope) first and that results in having to drop the pointcloud extension which cascades to dropping your types and-so-on...
If there is a way of replacing the function without having to drop the extension that would help, but I'm not aware of any.

**Comment by elemoine** [comment]
Yep, this is why I think we need to take this seriously and add back `PC_Envelope` as it was before. We could still add `PC_EnvelopeAsBinary`, which `PC_Envelope` would be an alias to.

And in `pointcloud_postgis` we could have `PC_EnvelopeGeometry` (and `PC_BoundingDiagonalGeometry`) instead of `PC_Envelope`. @mbredif what do you think?

**Comment by elemoine** [comment]
In case this is not clear this is what I am proposing right now: https://github.com/pgpointcloud/pointcloud/compare/master...elemoine:envelope.

**Comment by elemoine** [comment]
Fixed with https://github.com/pgpointcloud/pointcloud/pull/164 and https://github.com/pgpointcloud/pointcloud/issues/170.

**Comment by elemoine** [comment]
@tomvantilburg Thanks a lot for the bug report and your support with this.
