### ISSUE TITLE
pc_patch_ght.c:166:25: error: PCSCHEMA

### ISSUE THREAD

**Issue by animecomico** [pgpointcloud/pointcloud#175]
Hi,
I have this error in build master branch: 
pointcloud/lib/pc_patch_ght.c:166:25: error: ‘PCSCHEMA {aka const struct <anonymous>}’ has no member named ‘x_position’
     if ( j == pa->schema->x_position || j == pa->schema->y_position )

This mi CMake Build configuration(GHT tags/v0.1.0):
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting POINTCLOUD build type - RelWithDebInfo
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file getopt.h
-- Looking for include file getopt.h - found
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.3") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found CUnit: /usr/lib/x86_64-linux-gnu/libcunit.so  
-- Found LibGHT: /usr/local/lib/libght.so  
-- Found LazPerf: /usr/local/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/carlo/Downloads/UbuntuInstalls/pgpointcloud/pointcloud-build

**Comment by animecomico** [comment]
I see that in ../pointcloud/lib/pc_api.h in PCSCHEMA not exists x_position.
I  see exists pointer to xdim and ydim.

So i change to xdim->position and ydim->position where exists x_position and y_position.

This fix problem with x-position and y_postion.

Another error is with ../pointcloud/lib/cunit/cu_pc_patch.c, error by many arguments in the functions when in ../pointcloud/lib/pc_api.h the function is defined with 3 arguments.

So, in ../pointcloud/lib/cunit/cu_pc_patch.c:
pat1 = pc_patch_set_schema(pat0, simpleschema, 1, 0.0);
change by:
pat1 = pc_patch_set_schema(pat0, simpleschema, 1);

Buil succesfully.

**Comment by elemoine** [comment]
The problem is that we don't build with GHT enabled in Travis. Some time ago, I suggested to change that in https://github.com/pgpointcloud/pointcloud/pull/134, but I did not receive much echo :) I should probably go ahead and create a new PR for this.

**Comment by animecomico** [comment]
Ok.
