### ISSUE TITLE
Any docker images?

### ISSUE THREAD

**Issue by histfuture** [pgpointcloud/pointcloud#178]
Are there any docker files or pre-build images for this project?

**Comment by elemoine** [comment]
There is no "official" Docker image for the project right now. There is [benoc008/pgpointcloud](https://hub.docker.com/r/benoc008/pgpointcloud/) on Docker Hub that you might to try. I would be +1 to add a Dockerfile to pointcloud, based on the official [postgres image](https://hub.docker.com/_/postgres/).

**Comment by nangong** [comment]
The image [benoc008/pgpointcloud](https://hub.docker.com/r/benoc008/pgpointcloud/)  works, but we still hope a official support of docker images. 

BTW , this project is great.

**Comment by elemoine** [comment]
@nangong a PR for this is welcome.

**Comment by elemoine** [comment]
FYI, I've started working in a branch for this. See https://github.com/pgpointcloud/pointcloud/compare/master...elemoine:docker.

**Comment by strk** [comment]
https://github.com/vpicavet/docker-pggis also has PointCloud

**Comment by strk** [comment]
@elemoine any chance to share effort with @vpicavet on that ?

**Comment by pblottiere** [comment]
A Docker image is now available (see https://pgpointcloud.github.io/pointcloud/download.html#docker-hub) as well as corresponding building scripts (https://github.com/pgpointcloud/pointcloud/tree/master/docker).
