### ISSUE TITLE
How to test under CMake

### ISSUE THREAD

**Issue by robe2** [pgpointcloud/pointcloud#18]
Can't for the life of me figure out how to make check under cmake.  I asked and you said you aren't sure it's doable, so am ticketing.

**Comment by strk** [comment]
Are you guys not hit by #26, that you can build with cmake ?

**Comment by elemoine** [comment]
FWIW this [commit](https://github.com/elemoine/pointcloud/commit/af29744ecb84054cf01acf13d3b7e7e1492ab84f) to my `cmake` branch includes cmake configuration adding `check` and `installcheck` targets.

**Comment by strk** [comment]
@elemoine sending a PR next ?

**Comment by elemoine** [comment]
> @elemoine sending a PR next ?

Indeed: https://github.com/pgpointcloud/pointcloud/pull/129
