### ISSUE TITLE
How to load data from a pcd file?

### ISSUE THREAD

**Issue by nangong** [pgpointcloud/pointcloud#181]
I store my point cloud data in PCD files , are there any approaches to load this kind of data?

**Comment by nangong** [comment]
I found that , 
{
  "pipeline":[
    {
      "type":"readers.pcd",
      "filename":"inputfile.pcd"
    },
    {
      "type":"writers.text",
      "filename":"outputfile.txt"
    }
  ]
}
close this issued.

**Comment by elemoine** [comment]
Yes, PDAL supports the [Point Cloud Data](http://pointclouds.org/documentation/tutorials/pcd_file_format.php) file format. There is a [reader](https://www.pdal.io/stages/readers.pcd.html) and a [writer](https://www.pdal.io/stages/writers.pcd.html).
