### ISSUE TITLE
Pull sort_r fix for other BSDs

### ISSUE THREAD

**Issue by landryb** [pgpointcloud/pointcloud#186]
I've had sort_r fixed on OpenBSD here: https://github.com/noporpoise/sort_r/commit/1eb3da5945bfb753b56e389379795f1408b152e1

Can you pull it into the copy in lib/ ? This way pgpointcloud builds/runs fine on OpenBSD.

**Comment by elemoine** [comment]
Sounds good to me. Do you mind creating a PR for this?
