### ISSUE TITLE
 ERROR:  function pc_patch(double precision[], integer) does not exist  . pc_patch Error 

### ISSUE THREAD

**Issue by ahmadshabbir2468** [pgpointcloud/pointcloud#193]
Hi. 

We try Change Value of Classification Column and Fellow this https://lists.osgeo.org/pipermail//pdal/2016-May/000989.html !

But Unforuntly Stuck on this Line 
WITH my_patch AS (
   SELECT id as patch_id ,pa
     FROM medford 
     LIMIT 1
)
, my_points AS ( --converting patch to point. Note that could have bee done directly in the previous CTE
     SELECT patch_id, point[1:4] || '{7}'  || point[6:16] AS updated_array
     FROM my_patch , pc_explode(pa) as pt, pc_get(pt) as point
 )

, updated_patch AS (
     SELECT patch_id,

>  **pc_patch(updated_array,60) AS n_patch**-

- pc_patch(updated_array,60) AS n_patch
     FROM my_points
     GROUP BY patch_id
 )
  select * from my_points

> **ERROR:  function pc_patch(double precision[], integer) does not exist
> LINE 13:      SELECT patch_id, pc_patch(updated_array,60) AS n_patch-...**

                               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
********** Error **********

ERROR: function pc_patch(double precision[], integer) does not exist
SQL state: 42883
Hint: No function matches the given name and argument types. You might need to add explicit type casts.
Character: 374

Thanks in advance

**Comment by elemoine** [comment]
I'd recommend using ` and/or ``` to properly format your message.  See https://guides.github.com/features/mastering-markdown/ for example.

**Comment by ahmadshabbir2468** [comment]
WITH my_patch AS (-- spatial join. Should be very fast, both table indexed
    SELECT patch_id, patch
     FROM patch_table, polygon_table
     WHERE ST_Intersects(patch::geometry,geom)=TRUE
 )
 , my_points AS ( --converting patch to point. Note that could have been
 done directly in the previous CTE
     SELECT patch_id, point[1:6]|| my_new_class_id||point[8:n_dims] AS
 updated_array
     FROM my_patch, pc_explode(patch) as pt, pc_get(pt) as point
 )
 , updated_patch AS (
     SELECT patch_id, **_# pc_patch(updated_array,XX) AS n_patch_**
    FROM my_points
     GROUP BY patch_id
 )

**Comment by elemoine** [comment]
The `PC_Patch` function signature is `PC_Patch(pts pcpoint[]) `. It's an aggregator function that aggregates points into patches. So the way you use it above is not appropriate.

In your case, as I understand it, you want to create points and patches with different dimensions than the original points/patches.

First of all, you will need a new pointcloud schema (in the `pointcloud_formats` table) for the new points. Then, you can use the `PC_MakePoint` function to create new points, and `PC_Patch` to create patches from those new points.
