### ISSUE TITLE
Drop cmake

### ISSUE THREAD

**Issue by elemoine** [pgpointcloud/pointcloud#200]
Both the autotools and cmake can currently be used for building Pointcloud. Maintaining both is a bit of a burden.

We use the autotools on Travis, so autotools is what's tested currently. Also, @robe2 also uses the autotools for building packages for Windows.

So the easiest path is to drop cmake. Are there objections? If not I can create a PR for this.

**Comment by pblottiere** [comment]
> So the easiest path is to drop cmake. 

+1!

**Comment by elemoine** [comment]
Thank you for the feedback @pblottiere and @robe2. I'll work on it.
