### ISSUE TITLE
Tag and release v1.1.0

### ISSUE THREAD

**Issue by elemoine** [pgpointcloud/pointcloud#204]
Do people agree with tagging and releasing v1.1.0?

If there's no pushback I'll do that in the coming days.

**Comment by mbredif** [comment]
+1
If you have the time, maybe we could include #112 as well. As I recall it introduced a test to exhibit a memory leak and fixed it nicely (including setting up properly null values)

**Comment by elemoine** [comment]
> If you have the time, maybe we could include #112 as well. As I recall it introduced a test to exhibit a memory leak and fixed it nicely (including setting up properly null values)

Yep, I can have another look, but I am not sure about it.

**Comment by mbredif** [comment]
#205 I quickly reviewed the readme for our communication on deprecation and found a small typo. maybe we should drop support for the deprecated `PC_Envelope` in 1.2 instead of 2.0 (which seems far away)

**Comment by elemoine** [comment]
v1.1.0 is tagged, see https://github.com/pgpointcloud/pointcloud/releases.
