### ISSUE TITLE
Parallel safe function marker for PostgreSQL 9.6+

### ISSUE THREAD

**Issue by robe2** [pgpointcloud/pointcloud#209]
At a glance looks like all the functions in pgpointcloud and postgis_pointcloud extensions can be marked parallel safe which would allow queries to  at very least be split across workers where beneficial.

Right now noe of the queries using point cloud functions will be able to take advantage of parallel support.

**Comment by elemoine** [comment]
I've been wanting to look at that :)

**Comment by tsl-karlp** [comment]
@robe2 : Just FYI, we're been working on a PR at #218 to support `PARALLEL SAFE` for PG 9.6+.
