### ISSUE TITLE
CREATE EXTENSION pointcloud fails against PostgreSQL 10

### ISSUE THREAD

**Issue by zxcvb54321** [pgpointcloud/pointcloud#225]
When I try to create extension pointcloud I get the error:

ERROR:  could not load library "/usr/lib/postgresql/10/lib/pointcloud-1.1.so": /usr/lib/postgresql/10/lib/pointcloud-1.1.so: undefined symbol: Float8GetDatum

********** Error **********

ERROR: could not load library "/usr/lib/postgresql/10/lib/pointcloud-1.1.so": /usr/lib/postgresql/10/lib/pointcloud-1.1.so: undefined symbol: Float8GetDatum
SQL state: XX000

**Comment by elemoine** [comment]
Do you build the Pointcloud extension yourself?

If so make sure you run `make clean` before building Pointcloud for PostgresSQL 10?

As mentioned in the [SO response](https://stackoverflow.com/a/45595430/1064422): "PostgreSQL upstream changed DatumGetFloat8 from an external function to an inlined one for PG 10, so if you happened to build PL/Java against an older PG version, it would still be trying to link an external DatumGetFloat8 that, in PG 10, isn't there any more".

**Comment by elemoine** [comment]
Closing this. Please reopen if you're still having issues with Pointcloud and Postgres 10.
