### ISSUE TITLE
possibly typo in pc_patch_dimensional_compute_extent

### ISSUE THREAD

**Issue by prclibo** [pgpointcloud/pointcloud#23]
Hi, [line 197 and 198](https://github.com/pramsey/pointcloud/blob/master/lib/pc_patch_dimensional.c#L197) in `pc_patch_dimensional_compute_extent`, should be: 

    ymin = pc_value_scale_offset(___ymin___, pdl->schema->dims[pdl->schema->y_position]);
    ymax = pc_value_scale_offset(___ymax___, pdl->schema->dims[pdl->schema->y_position]);

**Comment by strk** [comment]
makes sense to me. would you be able to produce a testcase clearly showing the effects of that, and guarding against future regressions ?

\cc @pramsey

**Comment by strk** [comment]
I guess such test could go here: https://github.com/pgpointcloud/pointcloud/blob/master/lib/cunit/cu_pc_patch.c

**Comment by strk** [comment]
I took care of the test myself, thanks.
