### ISSUE TITLE
Unable to enable lazperf

### ISSUE THREAD

**Issue by trey-stafford** [pgpointcloud/pointcloud#231]
According to the pointcloud README, I should be able to optionally enable lazperf support by building laz-perf from source, and then setting the root laz-perf directory when configuring pointcloud.

I followed the directions to build laz-perf from source, and then ran `configure --with-lazperf=<path-to-laz-perf>`, but LazPerf is still disabled.

```
root@d5b203dae201:/pointcloud# ./configure --verbose --with-lazperf=/laz-perf/

checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for cpp... /usr/bin/cpp
checking for git... yes
checking for .git... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for inflate in -lz... yes
checking CUnit/CUnit.h usability... no
checking CUnit/CUnit.h presence... no
checking for CUnit/CUnit.h... no
checking for pg_config... /usr/bin/pg_config
checking PostgreSQL version... PostgreSQL 9.5.14
checking libpq-fe.h usability... yes
checking libpq-fe.h presence... yes
checking for libpq-fe.h... yes
checking for PQserverVersion in -lpq... yes
checking for xml2-config... /usr/bin/xml2-config
checking libxml/tree.h usability... yes
checking libxml/tree.h presence... yes
checking for libxml/tree.h... yes
checking libxml/parser.h usability... yes
checking libxml/parser.h presence... yes
checking for libxml/parser.h... yes
checking libxml/xpath.h usability... yes
checking libxml/xpath.h presence... yes
checking for libxml/xpath.h... yes
checking libxml/xpathInternals.h usability... yes
checking libxml/xpathInternals.h presence... yes
checking for libxml/xpathInternals.h... yes
checking for xmlInitParser in -lxml2... yes
checking laz-perf/las.hpp usability... no
checking laz-perf/las.hpp presence... no
checking for laz-perf/las.hpp... no
configure: creating ./config.status
config.status: creating config.mk
config.status: creating pgsql/Makefile
config.status: creating lib/pc_config.h
config.status: lib/pc_config.h is unchanged
config.status: creating pgsql/sqldefines.h
config.status: pgsql/sqldefines.h is unchanged

  PointCloud is now configured for

 -------------- Compiler Info -------------
  C compiler:           gcc -g -O2
  SQL preprocessor:     /usr/bin/cpp -traditional-cpp -w -P

 -------------- Dependencies --------------
  PostgreSQL config:    /usr/bin/pg_config
  PostgreSQL version:   PostgreSQL 9.5.14 (95)
  Libxml2 config:       /usr/bin/xml2-config
  Libxml2 version:      2.9.3
  LazPerf status:       disabled
  CUnit status:         disabled
```

Here's a Dockerfile that reproduces this issue: https://gist.github.com/trey-stafford/dca1f04c2cac80e51a65e6556cf09cc4

Tested with Ubuntu 16.04, pointcloud v1.2.0

**Comment by pblottiere** [comment]
Hi @trey-stafford,

I took a look on your Dockerfile, and I have some comments.

Firstly, you don't need to activate the Emscripten support to build laz-perf for PgPointcloud. Moreover, PgPointcloud configure script is waiting for an installation prefix, so you'll need to install LazPerf on your filesystem. By default, the prefix is `/usr/local`:

```
$ git clone https://github.com/verma/laz-perf.git
$ cd laz-perf
$ mkdir build
$ cd build
$ cmake ..
$ make
$ make install
```

Then, you have to indicate the installation prefix of Laz-Perf (`/usr/local`) to PgPointcloud configure script with `--with-lazperf`:

```
$ git clone https://github.com/pgpointcloud/pointcloud
$ cd pointcloud
$ ./autogen.sh
$ ./configure --with-lazperf=/usr/local/
...
  PointCloud is now configured for 

 -------------- Compiler Info ------------- 
  C compiler:           gcc -g -O2
  SQL preprocessor:     /usr/bin/cpp -traditional-cpp -w -P

 -------------- Dependencies -------------- 
  PostgreSQL config:    /usr/bin/pg_config
  PostgreSQL version:   PostgreSQL 9.5.14 (95)
  Libxml2 config:       /usr/bin/xml2-config
  Libxml2 version:      2.9.3
  LazPerf status:       /usr/local/include/laz-perf
  CUnit status:         disabled
```

Let me know and have a good day.

**Comment by LGRwx** [comment]
when I try to compiling the pointcloud, I run the configure script and get the infomation below, I have installed the lazperf in the default path but after I installed the lazperf successfully, I find the file which named las.hpp is still in the source code directory not in the /usr/local, so I cp it from the source-code directory to the /usr/local/include, but I still cannot enable the lazperf status,
`[root@test88 pointcloud]# ./configure --with-lazperf=/usr/local/
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for cpp... /usr/bin/cpp
checking for git... yes
checking for .git... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for inflate in -lz... yes
checking CUnit/CUnit.h usability... yes
checking CUnit/CUnit.h presence... yes
checking for CUnit/CUnit.h... yes
checking for CU_initialize_registry in -lcunit... yes
checking for pg_config... /usr/software/pgsql/bin/pg_config
checking PostgreSQL version... PostgreSQL 14.4
checking libpq-fe.h usability... yes
checking libpq-fe.h presence... yes
checking for libpq-fe.h... yes
checking for PQserverVersion in -lpq... yes
checking for xml2-config... /usr/bin/xml2-config
checking libxml/tree.h usability... yes
checking libxml/tree.h presence... yes
checking for libxml/tree.h... yes
checking libxml/parser.h usability... yes
checking libxml/parser.h presence... yes
checking for libxml/parser.h... yes
checking libxml/xpath.h usability... yes
checking libxml/xpath.h presence... yes
checking for libxml/xpath.h... yes
checking libxml/xpathInternals.h usability... yes
checking libxml/xpathInternals.h presence... yes
checking for libxml/xpathInternals.h... yes
checking for xmlInitParser in -lxml2... yes
checking laz-perf/las.hpp usability... no
checking laz-perf/las.hpp presence... no
checking for laz-perf/las.hpp... no
configure: creating ./config.status
config.status: creating config.mk
config.status: creating pgsql/Makefile
config.status: creating lib/pc_config.h
config.status: lib/pc_config.h is unchanged
config.status: creating pgsql/sqldefines.h
config.status: pgsql/sqldefines.h is unchanged

  PointCloud is now configured for 

 -------------- Compiler Info ------------- 
  C compiler:           gcc -g -O2
  SQL preprocessor:     /usr/bin/cpp -traditional-cpp -w -P

 -------------- Dependencies -------------- 
  PostgreSQL config:    /usr/software/pgsql/bin/pg_config
  PostgreSQL version:   PostgreSQL 14.4 (140)
  Libxml2 config:       /usr/bin/xml2-config
  Libxml2 version:      2.9.1
  LazPerf status:       disabled
  CUnit status:         enabled

[root@test88 pointcloud]# find / -name las.hpp
/home/jenkins/test/laz-perf/cpp/lazperf/las.hpp
find: ‘/proc/22598’: No such file or directory
/root/envsrc/laz-perf/cpp/lazperf/las.hpp
/usr/local/include/lazperf/las.hpp
`
