### ISSUE TITLE
Exporting lidar data

### ISSUE THREAD

**Issue by lovrth** [pgpointcloud/pointcloud#233]
(myenv) [root@localhost data]# pdal pipeline --input 2.json
PDAL: readers.pgpointcloud: Argument --spatialreference already exists.

**Comment by lovrth** [comment]
When I export data, spatialreference already exists, but the official document is written, thanks.

**Comment by carstoid** [comment]
having the same issue, installed 1.8 through conda on osx. 

running any pipeline involving readers.pgpointcloud appears to give the same error, doesn't matter whether or not spatialreference is specified in the pipeline .json file.

**Comment by pblottiere** [comment]
Already fixed: https://github.com/pgpointcloud/pointcloud/issues/241
