### ISSUE TITLE
1.2.0 incompatible with dimensionally compressed data inserted in 1.1.0

### ISSUE THREAD

**Issue by tomvantilburg** [pgpointcloud/pointcloud#242]
Considering the changes in: 
https://github.com/pgpointcloud/pointcloud/commit/063a5b16516c2a2752811da58d3ec81ff994f53f#diff-d7c7bdde4dd00cc24459067092b2844f

Where the enumeration for compression types is changed from:
`
PC_NONE = 0,
PC_GHT = 1,
PC_DIMENSIONAL = 2,
PC_LAZPERF = 3
`
to:
`
PC_NONE = 0,
PC_DIMENSIONAL = 1,
PC_LAZPERF = 2
`
it seems to me that existing data that was dimensionally compressed is now seen as lazperf compressed data (and subsequentially segfaulting postgres when trying to decompress as such).

Is my assumption correct that this is not backwards compatible?

**Comment by pblottiere** [comment]
(it is late, but better late than never :S)

> Is my assumption correct that this is not backwards compatible?

Yes indeed. I opened a PR to add a specific note about that point in the documentation (see https://github.com/pgpointcloud/pointcloud/pull/299). 

In the same time, I added a new tutorial chapter for removing the compression from a whole table of patches. This way you can:

1. duplicate your table of patches with dimension compression into a table without compression
2. update the pgpointcloud extension to 1.2.x
3. re-apply the compression you want 

It's not ideal but at least you don't have to import all your data from scratch...
