### ISSUE TITLE
3D (poly)line

### ISSUE THREAD

**Issue by k0kj** [pgpointcloud/pointcloud#245]
Hi, I'm Yuna.
I'm trying to find the way to insert 3D-line data into Postgresql database table.
And here, PcPoint data type supports 3D coordinate data type.
But I think PcPoint type ONLY supports the point of 3D, NOT a bunch of points which represents 3D-line.
Is it right? How can I insert 3D-line data?

**Comment by mbredif** [comment]
A pcpatch is just a list of points, which could be used to model a polyline.
However it is up to you to use a pcpatch with the semantics of a polylinez rather than what it was designed for (a multipointz).
