### ISSUE TITLE
Release to support PostgreSQL 12

### ISSUE THREAD

**Issue by robe2** [pgpointcloud/pointcloud#249]
Any chance we can have a release now that PostgreSQL 12 has been released?

It;'s a requirement for many packagers to package only released versions.

**Comment by elemoine** [comment]
@robe2 yep! I'll see if I can do more testing with Postgres 12 and create a new release. Thanks for the suggestion.

**Comment by elemoine** [comment]
@robe2 unfortunately my laptop is gone and I don't have an access to a Linux box at the moment, and until January. So I won't be able to do some testing with Postgres 12 and do a release.
@pblottiere would you by any chance have time for this?

**Comment by pblottiere** [comment]
Hi @elemoine,

> would you by any chance have time for this?

Yes, I'd be glad to help :). I can take a look within the next two weeks.

**Comment by df7cb** [comment]
Please have a look at #250 and #251 for the release, the future Debian package would need these resolved.

**Comment by df7cb** [comment]
Thanks! Working on getting the Debian package pass the regression tests now.
