### ISSUE TITLE
Regression tests fail if lazperf is not enabled

### ISSUE THREAD

**Issue by df7cb** [pgpointcloud/pointcloud#251]
```
--- /home/cbe/projects/postgresql/pointcloud/pointcloud/pgsql/expected/pointcloud-laz.out	2018-08-22 11:36:04.000000000 +0200
+++ /home/cbe/projects/postgresql/pointcloud/pointcloud/pgsql/results/pointcloud-laz.out	2019-12-13 15:59:26.630093220 +0100
@@ -77,80 +77,71 @@
     pa PCPATCH(5)
 );
 \d pa_test_laz
-                           Table "public.pa_test_laz"
- Column |    Type    |                        Modifiers                         
---------+------------+----------------------------------------------------------
- id     | integer    | not null default nextval('pa_test_laz_id_seq'::regclass)
- pa     | pcpatch(5) | 
+                              Table "public.pa_test_laz"
+ Column |    Type    | Collation | Nullable |                 Default                 
+--------+------------+-----------+----------+-----------------------------------------
+ id     | integer    |           | not null | nextval('pa_test_laz_id_seq'::regclass)
+ pa     | pcpatch(5) |           |          | 
 
 INSERT INTO pa_test_laz (pa) VALUES ('0000000005000000000000000200000002000000030000000500060000000200000003000000050008');
+ERROR:  pc_patch_lazperf_from_uncompressed: lazperf support is not enabled
+LINE 1: INSERT INTO pa_test_laz (pa) VALUES ('0000000005000000000000...
+                                             ^
...
```

lazperf is not in Debian, so we can't use it.

Is a Debian package even useful if that wouldn't be included? @strk?

**Comment by strk** [comment]
I think a Debian package would be useful. Why not adding lazperf debian package as well ?
(where did I suggest that, btw ? I lost track of that)

**Comment by pblottiere** [comment]
> Why not adding lazperf debian package as well ?

Yes, it would be awesome :+1:

**Comment by pblottiere** [comment]
Hi @df7cb,

Regression tests for laz compression should not be executed if lazperf is not enabled thanks to the next Makefile statement: https://github.com/pgpointcloud/pointcloud/blob/master/pgsql/Makefile.in#L35:L37

I just tested on my Archlinux and I didn't succeed in reproducing the issue. Can you give me the Debian version that you're currently using please? This way I'll try to reproduce the issue within a Docker container.

Thanks!

**Comment by df7cb** [comment]
@strk, you suggested it on #postgis on Nov 28th. :smiley:

For packaging lazperf, I don't even know what it is, and I'm not keen to maintain even more things. A "simple" PG extension package like pointcloud would be no problem, but more libraries... you'd need to find someone else to do that.

@pblottiere: That's on Debian unstable. But retrying the build, the regression file is excluded, so ignore this please.

Still, would a Debian package without lazperf be useful to anyone? I understood that pointcloud is used somewhere in the PostGIS/OSGeo infrastructure.

**Comment by pblottiere** [comment]
Hi @df7cb,

> For packaging lazperf, I don't even know what it is, and I'm not keen to maintain even more things. A "simple" PG extension package like pointcloud would be no problem, but more libraries... you'd need to find someone else to do that.

AFAIAC, working on an official Debian package is a long standing idea, but I never dare to strike out. I could definitely try for lazperf, but would you be available in case I need some support?

**Comment by df7cb** [comment]
Sure, I can help with the packaging and even sponsor the actual uploads.

**Comment by pblottiere** [comment]
> Sure, I can help with the packaging and even sponsor the actual uploads. 

Awesome, thanks @df7cb :+1:. I will come back to you shortly about this topic.

> But retrying the build, the regression file is excluded, so ignore this please.

OK, I'm closing this issue then.
