### ISSUE TITLE
Doesn't correctly detect PostgreSQL 13 beta 1

### ISSUE THREAD

**Issue by robe2** [pgpointcloud/pointcloud#268]
I get this error when trying to compile against PostgreSQL 13 beta 1 under mingw64

> ../lib/pc_config.h:4:23: error: invalid suffix "PostgreSQL" on integer constant
>  #define PGSQL_VERSION 13PostgreSQL 13beta1
>                        ^~~~~~~~~~~~
> pc_pgsql.h:118:5: note: in expansion of macro 'PGSQL_VERSION'
>  #if PGSQL_VERSION < 120
>      ^~~~~~~~~~~~~
> ../lib/pc_config.h:4:36: error: missing binary operator before token "13beta1"
>  #define PGSQL_VERSION 13PostgreSQL 13beta1
>                                     ^~~~~~~
> pc_pgsql.h:118:5: note: in expansion of macro 'PGSQL_VERSION'
>  #if PGSQL_VERSION < 120

**Comment by pblottiere** [comment]
Thanks for having raised the issue @robe2 :+1:

It should be fixed on master now.
