### ISSUE TITLE
Fix building on Alpine Linux

### ISSUE THREAD

**Issue by huggla** [pgpointcloud/pointcloud#277]
Hi!

I’m trying to build Pgpointclound on Alpine Linux but I get ”undefined reference to qsort_r”. It seems that qsort_r is not support in the musl libc on Alpine Linux. I found another application that encountered this problem and solved it. Could you please integrate this solution, or something similar, so building on Alpine becomes possible?

https://github.com/matz/streem/commit/62346ef1e544a065008c1a2ac7554d030bbfa381

Thanks
/Henrik

**Comment by pblottiere** [comment]
Hello @huggla,

I'm late on this issue but I just compiled pgpointcloud on a fresh Alpine docker image with succes. In any case, a `sort_r` implementation is already embedded and available thanks to the `CFLAGS=-DNESTED_QSORT=1` directive. 

I added a note in the documentation about that flag: https://github.com/pgpointcloud/pointcloud/pull/293.

Feel free to re-open the issue if necessary.
