### ISSUE TITLE
format schema namespace points to 404 URL

### ISSUE THREAD

**Issue by strk** [pgpointcloud/pointcloud#29]
The xmlns "pc" points to http://pointcloud.org/schemas/PC/1.1 which redirects to http://www.pdal.io/schemas/PC/1.1 which is a 404. This is probably a "pointcloud.org" issue, but I'm filing it here for reference as a start.

\cc @hobu

**Comment by strk** [comment]
The actual schema, as of 2012 (latest tag of PDAL) seems to be here:
https://github.com/PDAL/PDAL/blob/0.9.8/schemas/LAS.xsd

**Comment by hobu** [comment]
The pdal.io (old pointcloud.org) site is hosted on github pages. If you can make a pull request that does what we need to do against http://github.com/PDAL/pdal.github.io , that would be greatly appreciated.

**Comment by strk** [comment]
See how you like https://github.com/PDAL/pdal.github.io/pull/1 -- further redirect, not sure how would that work with xml validators (hadn't tried)

**Comment by strk** [comment]
works for me, after merge
