### ISSUE TITLE
Error during install compiled win64 version PointCloud extension ver. 1.2.2

### ISSUE THREAD

**Issue by gregjbb** [pgpointcloud/pointcloud#311]
After a successful build, during installation I got the following error :
"could not load library "d:/pgsql-12/lib/pointcloud-1.2.dll": The specified procedure could not be found." Postgresql version 12.11, PointCoud version 1.2.2, I  use  MinGW-w64 to build. xml2-2 installed. I have checked with depends and I see that all needed DLLs are in the system.

**Comment by robe2** [comment]
@gregjbb I'm not sure what your issue might be.  I build with mingw64 as well and don't have issue.

My binaries are here - if you want to try them -- https://winnie.postgis.net/download/windows/pg12/buildbot/extras/pointcloud-pg12-binaries-1.2.3w64gcc81.zip

If you indeed have all dependencies in place, it could be the version of the dependencies that it's picking up a different one from somewhere or you have the dependencies in the wrong folder.  They should be in bin of your pgsql-12 folder

**Comment by robe2** [comment]
Have 1.2.4 built for windows now.  One other dependency that pgpointcloud has is dependence on zlib.  So perhaps you are missing the zlib dependency or have wrong version in your postgresql path.

**Comment by pblottiere** [comment]
> Have 1.2.4 built for windows now

(thanks :tada:!)
