### ISSUE TITLE
Can we have a new release with PG16 support

### ISSUE THREAD

**Issue by robe2** [pgpointcloud/pointcloud#345]
PG16 came out a couple of days ago. We need a new release. Current last release does not support PG16

**Comment by robe2** [comment]
@pblottiere  Packagers are waiting.

**Comment by pblottiere** [comment]
Hello @robe2 and @df7cb,

Thanks for pointing that out, I'm taking a look.

**Comment by pblottiere** [comment]
Hello again @robe2,

I tried to activate PostGIS support with PostgreSQL 16 before doing the release (cf https://github.com/pgpointcloud/pointcloud/pull/346) but the `postgresql-16-postgis-3` package doesn't seem available in pgdg-snapshot.

Am I missing something?

**Comment by df7cb** [comment]
Hi,
since PG 16 has been released, everything is in `*-pgdg` now.

**Comment by pblottiere** [comment]
> since PG 16 has been released, everything is in *-pgdg now.

Oh yes, sorry for the dumb question :sweat:.

The new release is available : https://github.com/pgpointcloud/pointcloud/releases/tag/v1.2.5

Thanks for your work @robe2 and @df7cb.

**Comment by df7cb** [comment]
Thanks, Debian packages are happy!
