### ISSUE TITLE
Provide upgrade scripts

### ISSUE THREAD

**Issue by strk** [pgpointcloud/pointcloud#39]
There's currently no support for automatically generating upgrade scripts.
As new methods are added (for example the one in #38) the minor version number should increment.
As bugs are fixed (for example the one in #31) the micro version number should increment.
In both cases an upgrade script should be provided.

**Comment by strk** [comment]
I've pushed a 1.x branch for that version

**Comment by strk** [comment]
The upgrade doesn't work as is:
```
tt=# alter extension pointcloud update to '1.1';
ERROR:  relation "pointcloud_formats" already exists
```

**Comment by strk** [comment]
and the table is easy, harder is the type

**Comment by strk** [comment]
and aggregates, yay

**Comment by Remi-C** [comment]
By changing the MakeFile,
arn't you excluding the possiblity to use cmake?
Cheers,
Rémi-C

2015-02-12 13:23 GMT+01:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
I'm trying to keep CMake functional, but can't test as I'm affected with other bugs with cmake. Can you ?

**Comment by strk** [comment]
Another issue, pc_version() returns a 3-numbers version (1.0.0), but the script filename only has 2, which way should we go ? So far I've been using the 2-numbers schema.

**Comment by strk** [comment]
Which means tests should also be updated to conform:
https://travis-ci.org/pgpointcloud/pointcloud/builds/50481515

**Comment by Remi-C** [comment]
2 digits is not sufficient?
Cheers,
Rémi-C

2015-02-12 13:48 GMT+01:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
In a 3-numbers scheme you use:
```
 Major for backward incompatible API changes (or marketing hype)
 Minor for API additions
 Micro for fixes with unchanged API
```

With 2-numbers you would not have a way to distinguish between breaking and compatible API changes.

**Comment by Remi-C** [comment]
Ok,
I pulled your latest change and executed the following :
mkdir build
cd build
cmake ..
cd ..
make

No errors.
Cheers,
Rémi-C

2015-02-12 13:51 GMT+01:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
push further: make install && make installcheck

**Comment by strk** [comment]
also, see what gets installed

**Comment by Remi-C** [comment]
No target for installcheck

for install (with sudo)
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/lib/postgresql/9.3/lib/pointcloud.so
-- Installing: /usr/share/postgresql/9.3/extension/pointcloud--1.0.sql
-- Installing: /usr/share/postgresql/9.3/extension/pointcloud.control
-- Installing:
/usr/share/postgresql/9.3/extension/pointcloud_postgis--1.0.sql
-- Installing:
/usr/share/postgresql/9.3/extension/pointcloud_postgis.control


2015-02-12 13:56 GMT+01:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
no good, it should be "pointcloud--2.0.sql"

**Comment by strk** [comment]
To add to the confusion, the version tagged as "v0.1.0" installs pointcloud version 1.0 which advertises self as "1.0.0" from pc_version()
