### ISSUE TITLE
Make Install Fails (Ubuntu 14.04)

### ISSUE THREAD

**Issue by lyaunzbe** [pgpointcloud/pointcloud#45]
Hello! I've been trying to build this lib on Ubuntu 14.04. I've installed all the necessary deps, but get the following error when running make install:
![screen shot 2015-03-03 at 6 44 27 pm](https://cloud.githubusercontent.com/assets/28675/6477209/6f70ab6a-c1d5-11e4-8272-3b738fdc1b8d.png)

Any help would be much appreciated. Thank you!

**Comment by strk** [comment]
Could you please try #52 for me ? I can't use cmake here....

**Comment by strk** [comment]
For the record, #26 blocks me on testing cmake.
