### ISSUE TITLE
writers.pgpointcloud complains about too small capacity for no reason

### ISSUE THREAD

**Issue by strk** [pgpointcloud/pointcloud#48]
When writers.pgpointcloud gets handed a buffer bigger than the requested (via option) "capacity", it complains. But the driver doesn't really do anything with the configured "capacity", fully relying on the input to determine patch size, so why the error ?

It sounds like a left-over check from an aborted attempt to implement "chipper" locally.
Is that the case, @pramsey  ? Should that check be replaced by an "unused" warning or something like that ?

Note that receiving a smaller amount of points in input (--filters.chipper.capacity=300 --writers.pgpointcloud.capacity=500) does not result in any error or warning message and produces patches with 300 (not 500) points in it.

**Comment by strk** [comment]
Note that the problem was detected because --writers.pgpointcloud.capacity has a default size of 400 so even if you pretend no such option exists (which makes sense, since it's unused for anything but the error message) and use --filters.chipper.capacity to determine capacity, you fail unless you also raise --writers.pgpointcloud.capacity.

My suggestion is to just drop pgpointcloud.capacity.

**Comment by pramsey** [comment]
I can't think of a reason not to, which isn't necessarily indicative of anything.

**Comment by strk** [comment]
gah, this was another ticket placed in the wrong tracker.. you might have guessed it was for PDAL.

**Comment by strk** [comment]
For the record: https://github.com/PDAL/PDAL/pull/841

**Comment by Remi-C** [comment]
I was trying to understand, with no sucess :-(
Cheers,
Rémi-C

2015-03-18 15:33 GMT+01:00 Sandro Santilli <notifications@github.com>:
