### ISSUE TITLE
tests use system-installed plugins

### ISSUE THREAD

**Issue by strk** [pgpointcloud/pointcloud#49]
Rather than using the built plugins, testcases use the installed ones.
I'm pretty sure about this at least for the "pgpointcloudtest" case, not sure about the others.

**Comment by strk** [comment]
*TO BE CONFIRMED*

**Comment by pramsey** [comment]
You mean the online tests? (sql/expected)? that's "as built" pg_regress behaviour as far as I know. The alternative was something like the postgis regression system, which I consider a crime against nature. Was trying to stick to pgsql "best practices" as much as possible.

**Comment by strk** [comment]
I mean ``bin/pgpointcloudtest``, which is run as part of `make test`, but I now realize I'm filing this to the wrong tracker (was really for PDAL, sorry)
