### ISSUE TITLE
pc_pcid(pcpatch) and pc_pcid(pcpoint)

### ISSUE THREAD

**Issue by strk** [pgpointcloud/pointcloud#50]
For extracting "pcid" of patches and points.

**Comment by strk** [comment]
or is there a PostgreSQL function to extract typmod from a literal, for use with pc_typmod_pcid ?

**Comment by pramsey** [comment]
To my knowledge literals don't have typmods, they are just compared against the typmods of columns to make sure they are consistent. That is, there's nothing systemwide that could extract "a typmod" from a literal.

**Comment by strk** [comment]
Ok, so it still makes sense to have these new functions. I'll look at providing them. Thanks.
(for the record: RhodiumToad confirmed it ain't easy to do in SQL)

**Comment by Remi-C** [comment]
I got this in python,
but it is not good to expect that the user instal an unstrusted langage
Rémi-C

2015-03-18 17:04 GMT+01:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
Now (1.1.0) you have it in SQL too. Cheers !

**Comment by Remi-C** [comment]
Hmm tasty !
Cheers,
Rémi-C

2015-03-18 17:14 GMT+01:00 Sandro Santilli <notifications@github.com>:

**Comment by dustymugs** [comment]
+1

**Comment by strk** [comment]
After using them a couple of times I'm wondering.. should these be called PC_SchemaID or PC_FormatID or something clearer than PC_PCId ?

**Comment by Remi-C** [comment]
PC_PCID is realy close to ST_SRID,
both in concept and in syntax.


Cheers,
Rémi-C

2015-03-18 17:34 GMT+01:00 Sandro Santilli <notifications@github.com>:
