### ISSUE TITLE
ERROR:  pc_bytes_sigbits_encode: bits_encode cannot handle interpretation 8

### ISSUE THREAD

**Issue by strk** [pgpointcloud/pointcloud#61]
I was trying to convert a "double" GpsTime dimension to an uint8_t when I got this error:
```
ERROR:  pc_bytes_sigbits_encode: bits_encode cannot handle interpretation 8
```

If SIGBITS encoding does not support uint8_t it should not be candidated by caller code (bug).
Having it supported would be nice (enhancement).

**Comment by Remi-C** [comment]
This whole interpretation stuff is mysterious to me.
It is not described in the doc, and we don't know what is exactly stored
depending on the options

2015-04-02 13:42 GMT+02:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
Well, the XML has `size` and `interpretation` field. I indeed think that `interpretation` could imply `size`, given the list of known interpretations. Size would be more mysterious to me in that it doesn't tell how to interpret the bits taking the specified "size" space.

In this case I'm using `uint64_t` as the interpretation (an 8 bytes long integer).

**Comment by strk** [comment]
Interpretations are documented here: 
https://github.com/PDAL/PDAL/blob/master/schemas/LAS.xsd#L6-L14

**Comment by strk** [comment]
From the schema document I understand that `size` may be needed when the transporting software does not know the correct interpretation ("unknown") so it is still capable of skipping a value (for example).

**Comment by Remi-C** [comment]
yeah but

    This element describes how the data should be
    interpreted. In the case of conflicting data, for
    example when then size is 2, but the
    interpretation is "uint32_t", the size determines how
    much precision is available.


In my use case (I would like to use uint64_t bit it raises the same error
you got), it seems to work to use uint32_t + size 8.

Cheers,
Rémi-C

2015-04-02 13:51 GMT+02:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
Works fine means you do get full 64bit integer resolution ?
In PgPointcloud or elsewhere ?
Can you store (for example) 466741198050 in an uint32_t/8 value and get it back ?

**Comment by Remi-C** [comment]
Hm,
you are right

uint32_t / 8 and uint32_t / 4 give  the same wrong result(2578988031),
where int64_t/8 and int64_T/4 both gives correct results
 (46674119805)

More strange, the float64 seems to be fully brocken :
float64/8 and float64/4 :
4667411980500 ->
4667412054016 (7 digits correct, so float32 precision)

With "<pc:offset>4667410000000</pc:offset>"
float32 or 64 with / 4 or 8 works as intended.






2015-04-02 14:07 GMT+02:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
I'm adding support for sigbits encoding for 64bit integers

**Comment by strk** [comment]
@Remi-C support for 64bit integers is pushed, tests welcome :)

**Comment by Remi-C** [comment]
Damn you work so fast !
I will extensively use int64 with offset for my GPS_time data.

I will load several billions of points in base next week.

Cheers,
Rémi-C

2015-04-02 16:27 GMT+02:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
Do you really need 64bits _after_ an offset ?
How big is your timerange ?

**Comment by Remi-C** [comment]
0.1 ms over a day.
But I would like to be able to not use offset
(using one common universal time)

Cheers,
Rémi-C

2015-04-02 16:40 GMT+02:00 Sandro Santilli <notifications@github.com>:

**Comment by Remi-C** [comment]
@strk  
Confirmed,
I need 64 bits (for one digit :-/)
It was erroring before (damn 8 stuff).
With your patch it works !
