### ISSUE TITLE
Avoid compression cost in full dimension scan benchmarker

### ISSUE THREAD

**Issue by strk** [pgpointcloud/pointcloud#73]
Current benchmark tool for full patch scan uses a function that also incurs in possibly high compression costs for constructing the return of PC_FilterEquals. It'd be better to replace that call (or integrate it) with a read-only access.

**Comment by strk** [comment]
PC_AsText and PC_Explode are two possible candidates for full points scan. I'd like to find something that doesn't incur in string or rows building though...

**Comment by Remi-C** [comment]
From my experience pc_explode add a vast overhead (from memory, several
times the compression cost).
But I don't understand what you call 'benchmark tool for full patch scan'
Cheers


2015-04-16 17:36 GMT+02:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
https://github.com/pgpointcloud/pointcloud/blob/master/tools/benchmark.pl

**Comment by strk** [comment]
In particular, for the "full scan time" reported here:
https://github.com/pgpointcloud/pointcloud/blob/master/tools/benchmark.pl#L146
which is what I found to also include "compression time"...

**Comment by strk** [comment]
The ideal function would be one that scans all point values in a patch. Like a summary stats computer (but not using the pre-computed stats...)

**Comment by Remi-C** [comment]
Currently the pc_patchavg/max/min
seems to perform this scan (previous version where exploding)

2015-04-16 17:47 GMT+02:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
I cannot confirm. Pc_PatchAvg/Max/Min do an header scan, with no
need to decompress the dimensions (there are 3 uncompressed points
in the header)

**Comment by strk** [comment]
Here, this seems to be a good compromise:
```
[Table:raw20h64_1000_external Column:p]
 Dims: uint16,uint8,uint8,uint8,uint8,uint8,int8,uint8,uint16,double,double,double,double
 Patches: 8232
 Compression: dimensional
 Average patch size (bytes): 13265
 Average patch points: 999
 Total relation size: 1276 MB
 PC_PatchMax time (ms): 60.644/62.351/61.4975 (min/max/avg)
 PC_Envelope time (ms): 49.521/49.783/49.652 (min/max/avg)
 PC_Uncompress time (ms): 2470.612/2530.568/2500.59 (min/max/avg)
 PC_AsText time (ms): 37332.159/37653.224/37492.6915 (min/max/avg)
```

It clearly shows that PC_PatchMax does _not_ decompress, and it shows how much does it cost to produce JSON out of the uncompressed patch....

**Comment by strk** [comment]
And, PC_Explode turns out adding less overhead than PC_AsText !
```
 PC_AsText time (ms): 36878.942/36900.71/36889.826 (min/max/avg)
 PC_Explode time (ms): 6437.98/8083.242/7260.611 (min/max/avg)
```

**Comment by strk** [comment]
See #74 for optimizing PC_AsText somewhat
