### ISSUE TITLE
Reduce memory copies in PC_AsText

### ISSUE THREAD

**Issue by strk** [pgpointcloud/pointcloud#74]
The current PC_AsText function makes a string copy in pc_patch_uncompressed_to_string and another in pcpoint_as_text. The first one could be removed taking ownership of the stringbuffer data, as done by pcpatch_summary. 

The second one could be removed by passing a pre-initialized stringbuffer to the library function.

**Comment by strk** [comment]
The library uses its own "stringbuffer" implementation, which does not expose a way to transfer ownership of the internal buffer. I guess we can add that method, for making it usable with no copy at all (char *stringbuffer_releasestring, for example). Also it might be useful to add a "stringbuffer_reserve" to allocate an amount of memory up-front and avoid further reallocs...

@pramsey you said something about dropping use of our own custom class in favor of the pgsql one ?

**Comment by pramsey** [comment]
The one thing stringbuffer_t buys us is being able to run the cunit tests
100% independently of the postgres code base. Otherwise just using the
internal implementation would be fine. I'm not sure giving up the
separation is a great idea though.

**Comment by strk** [comment]
I think I'm happy enough with cd7a644 here.
Doing some math it makes sense for PC_AsText to take ~10x of PC_Explode for a 12-dimensions patch. This is because AsText makes a function call for each dimension in the point, while PC_Explode only makes 1 per point (point values are not extracted).

I'm testing this against ~8 million points organized in patches of 1000 point each.
It takes ~3.5 seconds to explode all patches and ~34 seconds to PC_AsText all patches.
Only 146ms to simply load them all in memory and ensuring they are uncompressed.
