### ISSUE TITLE
Allow lazperf as a patch compression type

### ISSUE THREAD

**Issue by strk** [pgpointcloud/pointcloud#81]
This is just an idea, currently.
See http://lists.osgeo.org/pipermail/pgpointcloud/2015-April/000153.html
Lazperf is https://github.com/verma/laz-perf

\cc @hobu

**Comment by pramsey** [comment]
+1

**Comment by elemoine** [comment]
With https://github.com/pgpointcloud/pointcloud/pull/105 merged this issue can be closed.
