### ISSUE TITLE
Add an HOWTO_RELEASE file

### ISSUE THREAD

**Issue by strk** [pgpointcloud/pointcloud#92]
let's make it easier to follow release procedure...

**Comment by strk** [comment]
PGXN might be involved (is it, @pramsey?)
In that case, see https://wiki.postgresql.org/wiki/PGXN and #91

**Comment by strk** [comment]
PGXN doesn't seem to be involved: http://pgxn.org/user/pramsey

Do you confirm, @pramsey ? Can we then maybe just drop META.json ? (see #91)

**Comment by pramsey** [comment]
If the release process is not going to involve updating a record on pgxn.org, then drop it. Shame to not be registered though.
