### ISSUE TITLE
pointcloud_abs_in and pointcloud_abs_out should not be volatile

### ISSUE THREAD

**Issue by robe2** [pgpointcloud/pointcloud#93]
I have to double check if I get this on lower than 9.5, so this might be a new thing  in 9.5,

When I do 

```

CREATE EXTENSION pointcloud;

```

I get these warnings:

```
WARNING:  type input function pointcloud_abs_in should not be volatile
WARNING:  type output function pointcloud_abs_out should not be volatile

```

**Comment by strk** [comment]
That's one of those things you can't easily upgrade.
But yes, it would be nice to fix for new installs.

**Comment by DBlasby** [comment]
I found this issue, too.  Is it something to ignore or is a problem?
